version: '2'
services:
  ripple:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    labels:
      lagoon.type: node
    environment:
      - AMAZEEIO_URL=ripple.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=3000
    ports:
      - "9001:3000"
