version: '2'
services:
  ripple:
    networks:
      - amazeeio-network
      - default
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'local'
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - amazeeio-network
      - default
    environment:
      LAGOON_ENVIRONMENT_TYPE: 'local'
    ports:
      - "9002:3000"
networks:
  amazeeio-network:
    external: true
