# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: integratedexperts/circleci2-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Pull newest Bay images.
          command: npm run bay:pull

      - run:
          name: Start Bay stack.
          command: |
            npm run bay:rebuild-full
            docker ps -a

      - run:
          name: Lint code.
          command: docker exec $(docker-compose ps -q ripple) npm run lint

      - run:
          name: Run tests
          command: docker exec $(docker-compose ps -q test) npm test

      - run:
          name: Install non-production packages into containers.
          command: |
            docker exec $(docker-compose ps -q ripple) /sbin/apk add --no-cache curl

      - run:
          name: prepare test directories.
          command: |
            docker exec $(docker-compose ps -q ripple) mkdir /app/screenshots

      - run:
          name: Test that Ripple site can be sereved.
          command: docker exec $(docker-compose ps -q ripple) curl -s -o /app/screenshots/ripple.html -w "%{http_code}" http://localhost:3000/ | grep -q 200

      - run:
          name: Collect artifacts.
          command: |
            mkdir -p /tmp/artifacts/ripple && docker cp $(docker-compose ps -q ripple):/app/screenshots /tmp/artifacts/ripple
          when: always

      - store_artifacts:
          path: /tmp/artifacts
